# syntax=docker/dockerfile:1
FROM public.ecr.aws/lambda/python:3.13 AS base

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    WDM_LOG_LEVEL=0 \
    CHROME_BINARY=/usr/bin/chromium \
    CHROMEDRIVER_BINARY=/usr/bin/chromedriver

ENV SE_MANAGER_STORAGE_PATH=/tmp \
    SE_STORAGE_DIR=/tmp \
    SE_CACHE_PATH=/tmp \
    SELENIUM_MANAGER_STORAGE_PATH=/tmp \
    HOME=/tmp \
    XDG_CACHE_HOME=/tmp/xdg-cache \
    XDG_CONFIG_HOME=/tmp/xdg-config \
    XDG_RUNTIME_DIR=/tmp/xdg-runtime

# Install Chromium & fonts for Selenium runs
RUN dnf install -y atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel nss mesa-libgbm jq unzip

# Copy and run the chrome installer script
COPY ./chrome-installer.sh ./chrome-installer.sh
RUN chmod +x ./chrome-installer.sh
RUN ./chrome-installer.sh
RUN rm ./chrome-installer.sh

COPY . .

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

CMD ["main.lambda_handler"]

